global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:3000']
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
